import os
import subprocess
import sys

import pytest


@pytest.mark.app
def test_streamlit_renders_every_horizon_in_isolated_process():
    # Streamlit/matplotlib can retain native resources between AppTest instances
    # on Windows.  The production smoke test intentionally uses the same process
    # boundary so a UI teardown cannot corrupt the orchestrator.
    code = (
        "from streamlit.testing.v1 import AppTest\n"
        "for horizon in (1, 2, 3, 4, 5):\n"
        "    app = AppTest.from_file('streamlit_app.py', default_timeout=90).run()\n"
        "    assert not app.exception, app.exception\n"
        "    landing_text = ' '.join(x.value for group in (app.markdown, app.success) for x in group)\n"
        "    assert 'Invest with evidence, not emotion.' in landing_text\n"
        "    assert 'AI-assisted portfolio decision engine' in landing_text\n"
        "    assert 'What Vriddhi does' in landing_text\n"
        "    app.sidebar.selectbox[0].set_value(horizon).run()\n"
        "    app.sidebar.button[0].click().run()\n"
        "    assert not app.exception, (horizon, app.exception)\n"
        "    text_groups = (app.markdown, app.info, app.success, app.warning, app.error, app.caption)\n"
        "    page_text = ' '.join(x.value for group in text_groups for x in group)\n"
        "    metric_labels = [x.label for x in app.metric]\n"
        "    assert 'What if you had started earlier?' in page_text, horizon\n"
        "    assert 'Actual Vriddhi Track Record' in page_text, horizon\n"
        "    assert 'Prospective evidence collection is active' in page_text, horizon\n"
        "    assert 'What should I do this month?' in page_text, horizon\n"
        "    assert 'health check-up for your investments' in page_text, horizon\n"
        "    assert all(action in page_text for action in ('PICK', 'DROP', 'TOP-UP', 'TRIM', 'HOLD')), horizon\n"
        "    assert '₹50,000 every month' in page_text, horizon\n"
        "    assert 'Why rebalance every month?' in page_text, horizon\n"
        "    assert 'Which stock will go up tomorrow?' in page_text, horizon\n"
        "    assert 'The two portfolios being compared' in page_text, horizon\n"
        "    assert 'Current portfolio —' in page_text, horizon\n"
        "    assert 'Previous portfolio —' in page_text, horizon\n"
        "    portfolio_tables = [x.value for x in app.dataframe if 'Whole Shares' in x.value.columns]\n"
        "    assert len(portfolio_tables) >= 3, (horizon, len(portfolio_tables))\n"
        "    action_tables = [x.value for x in app.dataframe if 'Action' in x.value.columns]\n"
        "    assert action_tables and 'Reason at a glance' in action_tables[0].columns, horizon\n"
        "    assert 'Rationale' not in action_tables[0].columns, horizon\n"
        "    assert 'Target change ₹' in action_tables[0].columns, horizon\n"
        "    assert 'Change in shares' in action_tables[0].columns, horizon\n"
        "    assert 'Change ₹' not in action_tables[0].columns, horizon\n"
        "    assert 'Change (shares)' not in action_tables[0].columns, horizon\n"
        "    assert 'Change in whole shares/month' not in action_tables[0].columns, horizon\n"
        "    if horizon == 5:\n"
        "        changes = action_tables[0].set_index('Stock')['Change in shares'].to_dict()\n"
        "        assert changes['BPCL'] == '+15.8', changes\n"
        "        assert changes['EICHERMOT'] == '+0.7', changes\n"
        "        assert changes['M&M'] == '+0.5', changes\n"
        "        assert changes['NTPC'] == '-9.5', changes\n"
        "    assert 'Actions to take now' in page_text, horizon\n"
        "    assert 'Why Vriddhi recommends this action' in page_text, horizon\n"
        "    assert page_text.count('Evidence in plain English:') >= len(action_tables[0]), horizon\n"
        "    assert page_text.count(\"How this supports Vriddhi's philosophy:\") >= len(action_tables[0]), horizon\n"
        "    assert 'Your monthly execution plan' in page_text, horizon\n"
        "    assert 'Combined execution sheet' in page_text, horizon\n"
        "    assert 'algorithm-friendly order sheet' in page_text, horizon\n"
        "    assert 'Gross calculation detail' in page_text, horizon\n"
        "    assert 'SELL first' in page_text, horizon\n"
        "    assert 'BUY — invest the SIP' in page_text, horizon\n"
        "    assert 'HOLD means retain and repeat the monthly purchase' in page_text, horizon\n"
        "    sip_inputs = [x for x in app.number_input if x.label == \"Current month's SIP amount (₹)\"]\n"
        "    assert len(sip_inputs) == 1 and sip_inputs[0].value == 100000, horizon\n"
        "    sell_tables = [x.value for x in app.dataframe if 'Estimated proceeds ₹' in x.value.columns]\n"
        "    buy_tables = [x.value for x in app.dataframe if 'Instruction' in x.value.columns and 'Estimated cost ₹' in x.value.columns]\n"
        "    net_tables = [x.value for x in app.dataframe if 'Cash after step ₹' in x.value.columns]\n"
        "    assert sell_tables and buy_tables and net_tables, horizon\n"
        "    assert any(x.startswith('BUY AGAIN · HOLD') for x in buy_tables[0]['Instruction']), horizon\n"
        "    if horizon == 5:\n"
        "        sells = sell_tables[0].set_index('Stock')['Shares'].to_dict()\n"
        "        assert sells == {'ADANIPORTS': 2, 'HEROMOTOCO': 1, 'NTPC': 8}, sells\n"
        "        buys = buy_tables[0].set_index('Stock')\n"
        "        assert buys.loc['COALINDIA', 'Instruction'] == 'BUY AGAIN · HOLD'\n"
        "        assert buys.loc['SUNPHARMA', 'Instruction'] == 'BUY AGAIN · HOLD'\n"
        "        assert buys.loc['BPCL', 'Instruction'] == 'BUY · new PICK'\n"
        "        net_instructions = net_tables[0]['Instruction'].tolist()\n"
        "        assert 'BUY 9 shares of NTPC' in net_instructions, net_instructions\n"
        "        assert not any('SELL' in x and 'NTPC' in x for x in net_instructions)\n"
        "        assert round(net_tables[0].iloc[-1]['Cash after step ₹']) == 156\n"
        "        execution_metrics = {x.label: x.value for x in app.metric}\n"
        "        assert execution_metrics['Estimated SELL proceeds'] == '₹11,199'\n"
        "        assert execution_metrics['Total BUY buying power'] == '₹111,199'\n"
        "        assert execution_metrics['Cash remaining'] == '₹156'\n"
        "        sip_inputs[0].set_value(50000).run()\n"
        "        assert not app.exception, (horizon, app.exception)\n"
        "        updated_metrics = {x.label: x.value for x in app.metric}\n"
        "        assert updated_metrics[\"This month's SIP\"] == '₹50,000'\n"
        "    assert 'Stock-by-stock decision cards' in page_text, horizon\n"
        "    assert page_text.count('Why this stock earned its place') >= 10, horizon\n"
        "    assert not any('Why these stocks?' in x.label for x in app.expander), horizon\n"
        "    assert page_text.count('Valuation in plain English') >= 10, horizon\n"
        "    assert page_text.count('Growth and contribution in plain English') >= 10, horizon\n"
        "    assert page_text.count('Risk in plain English') >= 10, horizon\n"
        "    assert page_text.count('Why it fits the whole portfolio') >= 10, horizon\n"
        "    assert 'Expected CAGR (base)' not in metric_labels, horizon\n"
        "    assert 'Validated OOS CAGR' in metric_labels, horizon\n"
        "    assert any(x.startswith('Historical portfolio CAGR') for x in metric_labels), horizon\n"
        "    assert 'Illustrative SIP value' in metric_labels, horizon\n"
        "    assert 'Why CAGR, not XIRR?' in page_text, horizon\n"
        "    assert 'Your risk, in one sentence' in page_text, horizon\n"
        "    assert 'Risk scorecard' in page_text, horizon\n"
        "    assert 'What could hurt this portfolio?' in page_text, horizon\n"
        "    assert 'If markets turn ugly: your investor playbook' in page_text, horizon\n"
        "    risk_tables = [x.value for x in app.dataframe if 'Risk lens' in x.value.columns]\n"
        "    assert risk_tables and len(risk_tables[0]) == 6, horizon\n"
        "    if horizon >= 2:\n"
        "        assert 'Why should I trust these results?' in page_text, horizon\n"
        "        assert 'How Vriddhi thinks' in page_text, horizon\n"
    )
    env = os.environ.copy()
    env["STREAMLIT_SERVER_ENABLE_CORS"] = "true"
    env["STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION"] = "true"
    env["STREAMLIT_LOGGER_LEVEL"] = "error"
    result = subprocess.run([sys.executable, "-c", code], timeout=300, env=env)
    assert result.returncode == 0
